import { useMemo, useState } from "react";

const conversations = [
  { id: "olivia", name: "Olivia Bennett", role: "Customer", initials: "OB", tone: "peach", preview: "Thanks, that works perfectly!", time: "2m", unread: 2, online: true, topic: "Reservation update", email: "olivia.bennett@email.com", phone: "+1 (415) 555-0198", orders: 12, spent: "$428.50", favorite: "Truffle Mushroom Pasta", reservation: "Tonight · 7:30 PM · Table 08", note: "Prefers a quiet table and sparkling water." },
  { id: "marcus", name: "Marcus Lee", role: "Kitchen Staff", initials: "ML", tone: "blue", preview: "We are short on basil for the 7 PM prep.", time: "18m", unread: 0, online: true, topic: "Ingredient availability", email: "marcus.lee@hearthtable.co", phone: "+1 (415) 555-0142", orders: 0, spent: "Internal", favorite: "Kitchen team", reservation: "Next shift · 4:00 PM", note: "Lead line cook · Downtown Kitchen." },
  { id: "sarah", name: "Sarah Mitchell", role: "Manager", initials: "SM", tone: "green", preview: "Can you review the delivery notes?", time: "1h", unread: 0, online: false, topic: "Delivery question", email: "sarah.mitchell@hearthtable.co", phone: "+1 (415) 555-0116", orders: 0, spent: "Internal", favorite: "Operations", reservation: "On duty · Until 11:00 PM", note: "Floor manager · Downtown Kitchen." },
  { id: "james", name: "James Anderson", role: "Customer", initials: "JA", tone: "purple", preview: "My order arrived missing the side salad.", time: "3h", unread: 1, online: false, topic: "Order issue", email: "james.anderson@email.com", phone: "+1 (415) 555-0173", orders: 7, spent: "$186.00", favorite: "Margherita Pizza", reservation: "No upcoming reservation", note: "Last order had a missing side salad." },
  { id: "rachel", name: "Rachel Kim", role: "Customer", initials: "RK", tone: "yellow", preview: "Is the patio available for Saturday?", time: "Yesterday", unread: 0, online: false, topic: "Table reservation", email: "rachel.kim@email.com", phone: "+1 (415) 555-0150", orders: 4, spent: "$142.25", favorite: "Salmon Avocado Bowl", reservation: "Requested · Sat · 6:00 PM", note: "Celebrating a birthday with 5 guests." },
];

const initialMessages = {
  olivia: [
    ["incoming", "Hi! I wanted to check if we can move our reservation to 7:30 PM tonight?", "7:12 PM"],
    ["outgoing", "Hi Olivia, absolutely. I’ve moved your reservation to 7:30 PM and kept your table by the window.", "7:14 PM · Read"],
    ["incoming", "Thanks, that works perfectly!", "7:16 PM"],
  ],
  james: [
    ["incoming", "My order arrived missing the side salad. Could you help me with that?", "4:42 PM"],
    ["outgoing", "I’m sorry about that, James. I’m checking with the kitchen now and will make this right.", "4:45 PM · Read"],
  ],
  marcus: [["incoming", "We are short on basil for the 7 PM prep. Should I swap in parsley?", "3:18 PM"], ["outgoing", "Yes, use parsley for tonight’s pesto and update the prep sheet.", "3:20 PM · Read"]],
  sarah: [["incoming", "Can you review the delivery notes before the driver arrives?", "2:04 PM"], ["outgoing", "On it. I’ll flag anything that needs a second look.", "2:08 PM · Read"]],
  rachel: [["incoming", "Is the patio available for Saturday? It’s for a birthday dinner.", "Yesterday"], ["outgoing", "It is. I’ve held a patio table for six at 6:00 PM while we confirm the details.", "Yesterday · Read"]],
};

function MessageIcon({ type }) {
  const paths = { search: "m21 21-4.3-4.3M10.8 18a7.2 7.2 0 1 1 0-14.4 7.2 7.2 0 0 1 0 14.4Z", filter: "M4 6h16M7 12h10M10 18h4", phone: "M6 3h3l2 5-2 1.5a15 15 0 0 0 5.5 5.5L16 13l5 2v3a3 3 0 0 1-3 3C10.3 21 3 13.7 3 6a3 3 0 0 1 3-3Z", video: "M15 8h4l2-2v12l-2-2h-4M3 6h12v12H3z", more: "M5 12h.01M12 12h.01M19 12h.01", paperclip: "m21 11.5-8.8 8.8a5.2 5.2 0 0 1-7.4-7.4l9.2-9.2a3.7 3.7 0 0 1 5.2 5.2l-9.2 9.2a2.2 2.2 0 0 1-3.1-3.1l8.5-8.5", smile: "M8 14s1.5 2 4 2 4-2 4-2M9 9h.01M15 9h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z", send: "m22 2-7 20-4-9-9-4Z M22 2 11 13" };
  return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={paths[type]} /></svg>;
}

export default function OwnerMessages() {
  const [activeId, setActiveId] = useState("olivia");
  const [search, setSearch] = useState("");
  const [message, setMessage] = useState("");
  const [threadMessages, setThreadMessages] = useState(initialMessages);
  const [showDetails, setShowDetails] = useState(true);
  const active = conversations.find((conversation) => conversation.id === activeId) || conversations[0];
  const visibleConversations = useMemo(() => conversations.filter((conversation) => `${conversation.name} ${conversation.preview} ${conversation.role}`.toLowerCase().includes(search.toLowerCase())), [search]);
  const sendMessage = () => { const text = message.trim(); if (!text) return; setThreadMessages((current) => ({ ...current, [activeId]: [...(current[activeId] || []), ["outgoing", text, "Now · Sent"]] })); setMessage(""); };

  return <div className="messages-page"><div className="messages-heading"><div><div className="orders-breadcrumb"><span>Workspace</span><b>/</b><strong>Messages</strong></div><h1>Messages <span className="unread-pill">3 unread</span></h1><p>Keep every guest, kitchen, and delivery conversation moving.</p></div><button className="primary-btn" type="button">＋ New message</button></div><div className="messages-workspace">
    <aside className="conversation-sidebar"><div className="conversation-top"><div><h2>Inbox <span>{conversations.filter((conversation) => conversation.unread).length}</span></h2><p>Recent conversations</p></div><button className="small-icon-button" type="button" aria-label="Filter messages"><MessageIcon type="filter" /></button></div><div className="conversation-search"><MessageIcon type="search" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search messages..." aria-label="Search messages" /></div><div className="conversation-tabs"><button className="active" type="button">All <span>8</span></button><button type="button">Customers</button><button type="button">Staff</button></div><div className="conversation-list">{visibleConversations.map((conversation) => <button key={conversation.id} type="button" className={`conversation-item ${activeId === conversation.id ? "selected" : ""}`} onClick={() => setActiveId(conversation.id)}><span className={`message-avatar avatar-${conversation.tone}`}>{conversation.initials}{conversation.online ? <i /> : null}</span><span className="conversation-copy"><span className="conversation-name"><b>{conversation.name}</b><small>{conversation.time}</small></span><span className="conversation-role">{conversation.role}</span><span className="conversation-preview">{conversation.preview}</span></span>{conversation.unread ? <em className="unread-count">{conversation.unread}</em> : null}</button>)}{!visibleConversations.length ? <div className="messages-empty">No conversations found.</div> : null}</div></aside>
    <section className="chat-panel"><header className="chat-header"><div className="chat-contact"><span className={`message-avatar avatar-${active.tone}`}>{active.initials}{active.online ? <i /> : null}</span><div><h2>{active.name}</h2><p><span className={active.online ? "online-dot" : "offline-dot"} />{active.online ? "Online now" : "Last seen earlier"} <b>·</b> {active.topic}</p></div></div><div className="chat-actions"><button type="button" aria-label="Call"><MessageIcon type="phone" /></button><button type="button" aria-label="Video call"><MessageIcon type="video" /></button><button type="button" aria-label="More options"><MessageIcon type="more" /></button></div></header><div className="chat-body"><div className="date-separator"><span>Today</span></div>{(threadMessages[activeId] || []).map(([direction, text, time], index) => <div key={`${text}-${index}`} className={`message-row ${direction}`}><div className="message-bubble"><p>{text}</p><span>{time}{direction === "outgoing" ? <b>✓✓</b> : null}</span></div></div>)}{activeId === "olivia" ? <div className="message-attachment"><div className="attachment-icon">▦</div><div><b>reservation-details.pdf</b><small>246 KB · Sent by you</small></div><button type="button">↓</button></div> : null}</div><div className="message-composer"><button type="button" className="composer-icon" aria-label="Attach file"><MessageIcon type="paperclip" /></button><input value={message} onChange={(event) => setMessage(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") sendMessage(); }} placeholder="Write a message..." aria-label="Write a message" /><button type="button" className="composer-icon" aria-label="Add emoji"><MessageIcon type="smile" /></button><button type="button" className="send-button" onClick={sendMessage} aria-label="Send message"><MessageIcon type="send" /></button></div></section>
    {showDetails ? <aside className="customer-panel"><div className="customer-panel-head"><h2>Contact details</h2><button type="button" onClick={() => setShowDetails(false)} aria-label="Close details">×</button></div><div className="customer-profile"><span className={`customer-large-avatar avatar-${active.tone}`}>{active.initials}</span><h3>{active.name}</h3><span className="role-badge">{active.role}</span><p>{active.email}</p><p>{active.phone}</p></div><div className="customer-detail-section"><h4>Customer overview</h4><div className="customer-stats"><span><b>{active.orders}</b><small>Total orders</small></span><span><b>{active.spent}</b><small>Lifetime value</small></span></div></div><div className="customer-detail-section"><h4>Favorite item</h4><div className="favorite-item"><span>✦</span><b>{active.favorite}</b></div></div><div className="customer-detail-section"><h4>Reservation</h4><p className="reservation-info">{active.reservation}</p></div><div className="customer-detail-section"><div className="notes-heading"><h4>Staff notes</h4><button type="button">Edit</button></div><p className="staff-note">{active.note}</p></div></aside> : <button className="show-details-button" type="button" onClick={() => setShowDetails(true)}>‹ Contact details</button>}
  </div></div>;
}
